import React from "react";
import LineChart from "./chart/LineChart";
import SectorHeatmap from "./chart/SectorHeatmap";
import LiveData from "./LiveData";
import MostActive from "./stock/MostActive";
import SectorRotation from "./SectorRotation";
function Dashboard(){
    return (
        <div className="dashboard">
            <LiveData/>
            <h1>Dashboard</h1>
            <p>This is the main page of Dashboard. Please note that all data are randomly generated by IEXCloud
                Sandbox API which are not accurate and it affects the general look of the site.
            </p>
            <div className="line_chart">
            <div><h5>SPY</h5><LineChart symbol="spy" range="1d" color="#AF8CFC"/></div>
            <div><h5>QQQ</h5><LineChart symbol="qqq" range="1d" color="#51EF96"/></div>
            <div><h5>IWM</h5><LineChart symbol="iwm" range="1d" color="#F5FF00"/></div>
            </div>
            <div className="sector-heatmap">
                <h4>MARKET OVERVIEW</h4>
                <p>Overview of the biggest market cap stocks in each sector.</p>
                 <div className="heatmap-chart">
                 <SectorHeatmap/>
                </div>
            </div>
            <div className="gainers-losers">
                <div className="gainers"><h4>Top Gainers</h4><MostActive request="gainers"/></div>
                <div className="losers"><h4>Top Losers</h4><MostActive request="losers"/></div>
            </div>
            <div className="dashboard-sector">
                <SectorRotation/>
            </div>
        </div>
    

    );
}


export default Dashboard;